layers:
  - function: lstm
    params: 
      in_channels: -1 # take size from config
      out_channels: 64
      kernel_size: 4
      stride: 2
      padding: 1

  - function: relu
    params: 
      negative_slope: 0.2
