layers:
  - function: lstm
    params:
      embedding_dim: <embedding_dim>
      hidden_dim: <hidden_dim>
      num_layers: 8
      bidirectional: True
      batch_first: True

  - function: leakyrelu
    params: 
      negative_slope: 0.2
