session_name: 'default_timeseries_test'

dataset:
  type: 'timeseries'
  name: 'nvda'
  target_column: Close
  batch_size: 32

nn:
  use_model: 'lstm_time_seq'
  load_weights: false
  params:
    seq_length: 40
    input_dim: 1
    hidden_dim: 4
    n_layers: 1

training:
  method: 'lstm'
  n_epochs: 1
  learning_rate: 1e-3

post_process:
  predict_series