session_name: 'default_text_test'

dataset:
  type: 'text'
  name: 'small_mock'
  batch_size: 64

nn:
  use_model: 'lstm_text'
  load_weights: false
  params:
    seq_length: 10
    embedding_dim: 36 * 4
    hidden_dim: 10
    num_layers: 20

training:
  method: 'sequence_prediction'
  n_epochs: 3
  learning_rate: 1e-3

post_process:
  generate_text