session_name: 'text_test'

dataset:
  type: 'text'
  name: 'mock'

nn_params:
  model_type: 'lstm'
  load_weights: false
  train_as: 'lstm'
  n_epochs: 1000
  learning_rate: 1e-3
  seq_length: 30
  embedding_dim: 500
  hidden_dim: 70

analysis:
  - 