session_name: 'default_image_test'

dataset:
  type: 'image'
  name: 'dogs'
  is_horizontal: false
  resize_ratio: 1 # keep at 1
  batch_size: 8


nn:
  use_model: 'vae'
  load_weights: false
  params:
    max_size: 128 # powers of 2
    latent_dim: 100

training:
  train_style: 'vae'
  n_epochs: 1
  learning_rate: 1e-3
  kl_betha: 1.3

analysis:
  - evaluate_and_interpolate
  - full_latent_analysis