session_name: 'default_image_test'

dataset:
  type: 'image'
  name: 'dogs'
  is_horizontal: false
  resize_ratio: 1 # keep at 1
  batch_size: 32


nn:
  use_model: 'vae'
  load_weights: false
  params:
    max_size: 128 # powers of 2
    latent_dim: 500

training:
  method: 'vae_reconstruction'
  n_epochs: 100
  learning_rate: 1e-3
  kl_betha: 1

post_process:
  - evaluate_and_interpolate
  - full_latent_analysis