session_name: 'sdf'

dataset:
  type: 'videos'
  name: 'clouds'
  is_horizontal: False
  resize_ratio: 1
  max_size: 128 # powers of 2

nn_params:
  model_type: 'vae' #resize_ratio > 1
  load_weights: false
  train_as: 'vae'
  n_epochs: 50
  latent_dim: 16
  learning_rate: 1e-3
  kl_betha: 1.3

analysis:
  - evaluate_and_interpolate
  - full_latent_analysis