session_name: 'flowers_testing'

dataset:
  type: 'images'
  name: 'flowers'
  is_horizontal: False
  resize_ratio: 1
  max_size: 128 # same as nn m.size

nn_params:
  max_size: 128 # same as dataset m.size
  model_type: 'vae' #resize_ratio > 1
  load_weights: false
  train_as: 'vae'
  n_epochs: 50
  latent_dim: 50
  learning_rate: 1e-3

analysis:
  - evaluate_and_interpolate
  - full_latent_analysis