dataset:
  name: 'flowers'
  type: 'images'
  is_horizontal: false
  resize_ratio: 4

nn_params:
  model_type: 'vae_sr'
  load_weights: false
  n_epochs: 400
  latent_dim: 15
  learning_rate: 1e-4

analysis:
  full_latent_analysis