session_name: 'clouds_testing'

dataset:
  type: 'images'
  name: 'flowers'
  is_horizontal: false
  resize_ratio: 4

nn_params:
  model_type: 'vae_sr'
  load_weights: false
  train_as: 'vae'
  n_epochs: 10
  latent_dim: 15
  learning_rate: 1e-4

analysis:
  full_latent_analysis